#![no_std]
#![no_main]

//! Blocking WiFi init test with phase colors.
//! Each phase writes a real WS2812 color frame generated by the RMT (with the
//! 300us reset folded into the final bit) so the LED reliably shows exactly
//! how far the firmware got.
//!
//! The pixel writing uses the same RMT driver as `src/main.rs`: the old inline
//! bit-bang here (`ws2812_bit`/`ws2812_byte`/`ws2812_grb`, ~1us phase delays)
//! had the same "one phase per bit" bug as the old `GpioPulse` driver — a
//! `1` bit ended in a ~0ns LOW so consecutive `1` bits merged into one pulse —
//! and `esp_hal::delay::Delay::delay_nanos` quantises to whole microseconds,
//! so a delay-based fix is impossible. The RMT emits both phases of every bit
//! with hardware timing at 12.5ns resolution.
//!
//!   RED        = firmware started (main entry)
//!   BLUE       = heap allocated
//!   YELLOW     = esp_rtos started
//!   MAGENTA    = WiFi station config ready
//!   WHITE      = right before WifiController::new()
//!   GREEN      = WifiController::new() OK
//!   Blink RED  = WifiController::new() failed — blinks N times where N is
//!                the numeric WifiError code (1=Unsupported, 2=InvalidArguments,
//!                3=Failed, 4=OutOfMemory, 5=InvalidSsid, 6=InvalidPassword,
//!                7=NotConnected, 8=any other variant), then pauses 1.5 s
//!                and repeats forever.

extern crate alloc;

use esp_hal::Blocking;
use esp_hal::{
    clock::CpuClock,
    delay::Delay,
    gpio::Level,
    interrupt::software::SoftwareInterruptControl,
    ram,
    rmt::{Channel, PulseCode, Rmt, Tx, TxChannelConfig, TxChannelCreator},
    time::Rate,
    timer::timg::TimerGroup,
};
use esp_radio::wifi::{
    sta::StationConfig, Config as WifiConfig, ControllerConfig, WifiController, WifiError,
};
use led_core::wifi as led_wifi;
use led_core::ws2812::{encode_rgb_v2, Ws2812FrameV2};

use esp_println::println;

esp_bootloader_esp_idf::esp_app_desc!();
use esp_backtrace as _;

// ── WS2812 driver: RMT hardware timing (same as src/main.rs) ───────────

/// RMT global counter clock (MHz). The ESP32-C5 RMT source clock is the 80 MHz
/// PLL (the driver's `ClockSource::default()`), so requesting 80 MHz is exact:
/// the global divider resolves to "no division" and one tick = 1 / 80 MHz =
/// 12.5 ns.
const RMT_SCLK_MHZ: u32 = 80;

/// Per-channel clock divider. It is written VERBATIM to the channel `div_cnt`
/// register, on the ESP32-C5 where `1` means "no division" (full 80 MHz) — NOT
/// the default `0`, which is the register's special "divide by 256" value.
/// Using the default would make each tick 3.2 µs and push every WS2812 phase
/// far outside its ±150 ns datasheet window.
const CHANNEL_CLK_DIVIDER: u8 = 1;

/// Nanoseconds per second (for the ns→tick conversion).
const NS_PER_SEC: u64 = 1_000_000_000;

/// Convert a nanosecond width to RMT ticks at `tick_hz`.
///
/// `ticks = ns × tick_hz / 1e9`. All four WS2812 phase widths (400/850/800/450
/// ns) and the 300 µs reset are exact multiples of the 12.5 ns tick, so this
/// is exact; the assertion guards against a future constant that would not
/// divide evenly (which would need rounding and could push a phase outside its
/// ±150 ns window).
fn ns_to_ticks(ns: u32, tick_hz: u32) -> u16 {
    let scaled = ns as u64 * tick_hz as u64;
    debug_assert_eq!(
        scaled % NS_PER_SEC,
        0,
        "{ns} ns is not an exact multiple of the {tick_hz} Hz tick"
    );
    (scaled / NS_PER_SEC) as u16
}

/// Build the 25-entry pulse-code frame (24 bits + end marker) for one color.
///
/// `encode_rgb_v2` already applied the RGB→GRB wire-order conversion and emits
/// both phases of every bit; each bit becomes one `PulseCode` (High for
/// `high_ns`, then Low for `low_ns`). The 300 µs reset LOW is folded into the
/// final bit's LOW phase — both are contiguous Low, so the waveform is
/// identical, and `low_ticks + reset_ticks` stays below the 15-bit (32767)
/// per-field maximum.
fn frame_codes(frame: &Ws2812FrameV2, tick_hz: u32) -> [PulseCode; 25] {
    let mut codes = [PulseCode::end_marker(); 25];
    for (i, phase) in frame.pixel.iter().enumerate() {
        let high = ns_to_ticks(phase.high_ns, tick_hz);
        let mut low = ns_to_ticks(phase.low_ns, tick_hz);
        if i + 1 == frame.pixel.len() {
            low += ns_to_ticks(frame.reset_ns, tick_hz);
        }
        codes[i] = PulseCode::new(Level::High, high, Level::Low, low);
    }
    codes[24] = PulseCode::end_marker();
    codes
}

/// Send one RGB color (`[R, G, B]`) to the WS2812 via the RMT.
///
/// Consumes the channel (RMT `transmit` takes ownership) and returns it once
/// the blocking `wait` confirms transmission completed. Per-frame blocking
/// time is ~330 µs, dominated by the 300 µs reset (previously ~74 µs under the
/// bit-bang driver).
fn ws2812_rgb_rmt<'a>(
    channel: Channel<'a, Blocking, Tx>,
    tick_hz: u32,
    rgb: &[u8; 3],
) -> Channel<'a, Blocking, Tx> {
    let frame = encode_rgb_v2(rgb);
    let codes = frame_codes(&frame, tick_hz);
    let tx = channel.transmit(&codes).unwrap();
    tx.wait().unwrap()
}

// ── Main ───────────────────────────────────────────────────────────────────

#[esp_hal::main]
fn main() -> ! {
    esp_println::logger::init_logger_from_env();

    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    let peripherals = esp_hal::init(config);

    let delay = Delay::new();

    // Configure the RMT at 80 MHz so one tick = 12.5 ns — the exact resolution
    // needed for the four WS2812 phase widths (400/850/800/450 ns).
    let rmt = Rmt::new(peripherals.RMT, Rate::from_mhz(RMT_SCLK_MHZ)).unwrap();
    // Read the *actual* counter frequency before moving `channel0` out of
    // `rmt` (a partial move leaves the whole struct unusable). With
    // `CHANNEL_CLK_DIVIDER == 1` the channel is undivided, so the channel tick
    // frequency equals the 80 MHz global sclk.
    let tick_hz = rmt.frequency().as_hz() / CHANNEL_CLK_DIVIDER as u32;

    let mut channel = rmt
        .channel0
        .configure_tx(&TxChannelConfig::default().with_clk_divider(CHANNEL_CLK_DIVIDER))
        .unwrap()
        .with_pin(peripherals.GPIO27);

    println!("=== WiFi phase test ===");

    // RED = started
    channel = ws2812_rgb_rmt(channel, tick_hz, &[255, 0, 0]);
    println!("[1] started, setting RED");

    // BLUE = heap
    esp_alloc::heap_allocator!(#[ram(reclaimed)] size: 64 * 1024);
    esp_alloc::heap_allocator!(size: 36 * 1024);
    channel = ws2812_rgb_rmt(channel, tick_hz, &[0, 0, 255]);
    println!("[2] heap allocated, setting BLUE");

    // YELLOW = RTOS started
    let timg0 = TimerGroup::new(peripherals.TIMG0);
    let sw_int = SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);
    esp_rtos::start(timg0.timer0, sw_int.software_interrupt0);
    channel = ws2812_rgb_rmt(channel, tick_hz, &[255, 255, 0]);

    // MAGENTA = WiFi station config ready
    // WiFi credentials come from configs/wifi.json (single source of
    // truth), parsed + validated by led-core before the driver is used.
    let creds = led_wifi::default_wifi_config().expect("wifi.json failed to parse");
    creds
        .validate()
        .expect("wifi.json credentials out of ESP32 limits");
    let station_config = WifiConfig::Station(
        StationConfig::default()
            .with_ssid(creds.ssid.as_str())
            .with_password(creds.password),
    );
    channel = ws2812_rgb_rmt(channel, tick_hz, &[255, 0, 255]);

    // WHITE = right before WifiController::new()
    channel = ws2812_rgb_rmt(channel, tick_hz, &[255, 255, 255]);
    println!("[5] WHITE set, about to call WifiController::new()");

    let _controller = match WifiController::new(
        peripherals.WIFI,
        ControllerConfig::default().with_initial_config(station_config),
    ) {
        Ok(c) => c,
        Err(e) => {
            println!("!!! WiFi init FAILED: {:?}", e);
            // Blink N times where N = error code, then pause, repeat.
            //   1 = Unsupported
            //   2 = InvalidArguments
            //   3 = Failed (ESP_FAIL from blob)
            //   4 = OutOfMemory
            //   5 = InvalidSsid
            //   6 = InvalidPassword
            //   7 = NotConnected
            let code: u32 = match e {
                WifiError::Unsupported => 1,
                WifiError::InvalidArguments => 2,
                WifiError::Failed => 3,
                WifiError::OutOfMemory => 4,
                WifiError::InvalidSsid => 5,
                WifiError::InvalidPassword => 6,
                WifiError::NotConnected => 7,
                _ => 8,
            };
            loop {
                for _ in 0..code {
                    channel = ws2812_rgb_rmt(channel, tick_hz, &[255, 0, 0]);
                    delay.delay_millis(80);
                    channel = ws2812_rgb_rmt(channel, tick_hz, &[0, 0, 0]);
                    delay.delay_millis(80);
                }
                delay.delay_millis(1500);
            }
        }
    };

    // GREEN = WifiController::new() OK
    // Last frame the channel ever receives (the idle loop below only sleeps),
    // so discard the returned channel rather than trigger `unused_assignments`.
    let _ = ws2812_rgb_rmt(channel, tick_hz, &[0, 255, 0]);
    println!("[6] WifiController::new() OK, setting GREEN");

    // Stay green (WiFi driver is initialized and idle)
    loop {
        delay.delay_millis(10_000);
    }
}
