//! Config-driven LED effects (sync/blocking), waveform generated by the RMT.
//!
//! Reads a JSON config from `configs/effects.json` and runs the specified
//! effects (blink and blend) in a loop. The config is embedded at compile
//! time using `include_str!`.
//!
//! All logic (config model, WS2812 encoding, color interpolation) lives in the
//! `led-core` crate and is unit+integration tested on the host; this binary is
//! the thin hardware layer.
//!
//! The WS2812 waveform is generated by the **RMT peripheral**, not GPIO
//! bit-banging. The previous `GpioPulse`/`replay_frame` driver timed only ONE
//! phase per bit: a `1` bit ended in a ~0 ns LOW, so consecutive `1` bits
//! merged into a single continuous HIGH pulse — a byte like `0xFF` collapsed
//! to one pulse and the 24-bit GRB frame misaligned, producing the garbled
//! colours seen on the board. A `delay_nanos`-based fix is impossible here:
//! `esp_hal::delay::Delay::delay_nanos` quantises to whole microseconds
//! (`Duration::from_micros(ns.div_ceil(1000))`), so all four phase widths
//! (400/850/800/450 ns) round up to 1 µs and a `0`-bit becomes indistinguishable
//! from a `1`-bit. The RMT emits BOTH phases of every bit with hardware timing
//! at 12.5 ns resolution.

#![no_std]
#![no_main]

extern crate alloc;

use esp_hal::delay::Delay;
use esp_hal::gpio::Level;
use esp_hal::rmt::{Channel, PulseCode, Rmt, Tx, TxChannelConfig, TxChannelCreator};
use esp_hal::time::Rate;
use esp_hal::Blocking;
use led_core::config::{LedConfig, LedEffect};
use led_core::ws2812::{encode_rgb_v2, Ws2812FrameV2};

esp_bootloader_esp_idf::esp_app_desc!();

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}

// ── WS2812 driver: RMT hardware timing over led-core's v2 encoding ──────────

/// RMT global counter clock (MHz). The ESP32-C5 RMT source clock is the 80 MHz
/// PLL (the driver's `ClockSource::default()`), so requesting 80 MHz is exact:
/// the global divider resolves to "no division" and one tick = 1 / 80 MHz =
/// 12.5 ns.
const RMT_SCLK_MHZ: u32 = 80;

/// Per-channel clock divider. It is written VERBATIM to the channel `div_cnt`
/// register, on the ESP32-C5 where `1` means "no division" (full 80 MHz) — NOT
/// the default `0`, which is the register's special "divide by 256" value.
/// Using the default would make each tick 3.2 µs and push every WS2812 phase
/// far outside its ±150 ns datasheet window.
const CHANNEL_CLK_DIVIDER: u8 = 1;

/// Nanoseconds per second (for the ns→tick conversion).
const NS_PER_SEC: u64 = 1_000_000_000;

/// Convert a nanosecond width to RMT ticks at `tick_hz`.
///
/// `ticks = ns × tick_hz / 1e9`. All four WS2812 phase widths (400/850/800/450
/// ns) and the 300 µs reset are exact multiples of the 12.5 ns tick, so this
/// is exact; the assertion guards against a future constant that would not
/// divide evenly (which would need rounding and could push a phase outside its
/// ±150 ns window).
fn ns_to_ticks(ns: u32, tick_hz: u32) -> u16 {
    let scaled = ns as u64 * tick_hz as u64;
    debug_assert_eq!(
        scaled % NS_PER_SEC,
        0,
        "{ns} ns is not an exact multiple of the {tick_hz} Hz tick"
    );
    (scaled / NS_PER_SEC) as u16
}

/// Build the 25-entry pulse-code frame (24 bits + end marker) for one color.
///
/// `encode_rgb_v2` already applied the RGB→GRB wire-order conversion and emits
/// both phases of every bit; each bit becomes one `PulseCode` (High for
/// `high_ns`, then Low for `low_ns`). The 300 µs reset LOW is folded into the
/// final bit's LOW phase — both are contiguous Low, so the waveform is
/// identical, and `low_ticks + reset_ticks` stays below the 15-bit (32767)
/// per-field maximum.
fn frame_codes(frame: &Ws2812FrameV2, tick_hz: u32) -> [PulseCode; 25] {
    let mut codes = [PulseCode::end_marker(); 25];
    for (i, phase) in frame.pixel.iter().enumerate() {
        let high = ns_to_ticks(phase.high_ns, tick_hz);
        let mut low = ns_to_ticks(phase.low_ns, tick_hz);
        if i + 1 == frame.pixel.len() {
            low += ns_to_ticks(frame.reset_ns, tick_hz);
        }
        codes[i] = PulseCode::new(Level::High, high, Level::Low, low);
    }
    codes[24] = PulseCode::end_marker();
    codes
}

/// Send one RGB color (`[R, G, B]`) to the WS2812 via the RMT.
///
/// Consumes the channel (RMT `transmit` takes ownership) and returns it once
/// the blocking `wait` confirms transmission completed. Per-frame blocking
/// time is ~330 µs, dominated by the 300 µs reset (previously ~74 µs under the
/// bit-bang driver).
fn ws2812_rgb_rmt<'a>(
    channel: Channel<'a, Blocking, Tx>,
    tick_hz: u32,
    rgb: &[u8; 3],
) -> Channel<'a, Blocking, Tx> {
    let frame = encode_rgb_v2(rgb);
    let codes = frame_codes(&frame, tick_hz);
    let tx = channel.transmit(&codes).unwrap();
    tx.wait().unwrap()
}

// ── Main ────────────────────────────────────────────────────────────────────

const CONFIG_JSON: &str = include_str!("../configs/effects.json");

#[esp_hal::main]
fn main() -> ! {
    let peripherals = esp_hal::init(esp_hal::Config::default());

    // Initialize heap allocator for serde_json / alloc
    esp_alloc::heap_allocator!(size: 8192);

    let delay = Delay::new();

    // Configure the RMT at 80 MHz so one tick = 12.5 ns — the exact resolution
    // needed for the four WS2812 phase widths (400/850/800/450 ns).
    let rmt = Rmt::new(peripherals.RMT, Rate::from_mhz(RMT_SCLK_MHZ)).unwrap();
    // Read the *actual* counter frequency before moving `channel0` out of
    // `rmt` (a partial move leaves the whole struct unusable). With
    // `CHANNEL_CLK_DIVIDER == 1` the channel is undivided, so the channel tick
    // frequency equals the 80 MHz global sclk.
    let tick_hz = rmt.frequency().as_hz() / CHANNEL_CLK_DIVIDER as u32;

    let mut channel = rmt
        .channel0
        .configure_tx(&TxChannelConfig::default().with_clk_divider(CHANNEL_CLK_DIVIDER))
        .unwrap()
        .with_pin(peripherals.GPIO27);

    // Parse config at startup (falls back to an empty config if malformed).
    let config: LedConfig =
        serde_json::from_str(CONFIG_JSON).unwrap_or_else(|_| LedConfig::empty());

    // Run effects in a loop. Each `ws2812_rgb_rmt` blocks ~330 µs (the 300 µs
    // reset dominates); that was ~74 µs under the bit-bang driver. Nothing
    // below assumed the old value — the per-color holds are the explicit
    // `delay_millis` calls.
    loop {
        for effect in &config.effects {
            match effect {
                LedEffect::Blink {
                    colors,
                    duration_ms,
                } => {
                    for &color in colors {
                        channel = ws2812_rgb_rmt(channel, tick_hz, &color);
                        delay.delay_millis(*duration_ms);
                    }
                }
                LedEffect::Blend {
                    from,
                    to,
                    steps,
                    step_ms,
                    ..
                } => {
                    for step in 0..=*steps {
                        let color = led_core::color::interpolate(from, to, step, *steps);
                        channel = ws2812_rgb_rmt(channel, tick_hz, &color);
                        delay.delay_millis(*step_ms);
                    }
                }
            }
        }
    }
}
